version: "3.8"

services:
  api:
    build: ./app
    container_name: api
    ports:
      - 8000:8000
    environment:
      DB_LOCAL: mongodb://db/empDB
    env_file:
      - ./app/.env

  db:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - empDB:/data/db

volumes:
  empDB:
